### PR TITLE
fix: show focus border for scrolling tabs

### LINKED ISSUE #987: Scrolling tabs focused tab display issue
**Describe the bug**

When a tab in scrolling tabs is focused, the top border isn't appearing: 
image

**To Reproduce**

Go here: https://atomic-react.security.cisco.com/components/tab#scrolling
click a tab, see missing top border

**Expected behavior**

The top border should be visible

**Additional context**

`.a-tab-group__tab-content` needs 1px top padding. After the change is made, the github action workflow `Update Snapshots` needs run on the published branch, and that should update the visual regression test assets

### PR DESCRIPTION
**Pull request by MizuhoOkimoto**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows semantic commit message guidelines
- [x] The changes are documented in component docs and changelog
- [x] The ESLint plugin has been updated if a new component is added
- [x] Test have been added or modified, if appropriate
- [x] Has been verified locally

**What kind of change does this PR introduce?**
Closes #987 
Please see this page: [https://atomic-react.security.cisco.com/components/tab#scrolling](https://atomic-react.security.cisco.com/components/tab#scrolling)
When clicking a tab, the top border is missing.
I added padding-top 1px, so that the top border became visible.

**Does this PR introduce a breaking change?** 
No

**Other information**:
Attached screenshot after fixing it.
image

If I need to improve or follow any rules to contribute, please let me know. Thank you very much!

### CODE REVIEW

**Review by frattaro — APPROVED** [review]

**Review by frattaro — CHANGES_REQUESTED** [review]
Can you add an entry in /framework/changelog.mdx? as
```
## 3.1.3 (pending)

- Fixed padding on scrolling tabs so focus border displays correctly
```

**Comment by frattaro** [comment]
@MizuhoOkimoto  Thanks, did it get pushed?

**Comment by MizuhoOkimoto** [comment]
Hi, @frattaro ! Yes, I pushed it. Was it okay to push...?
image
image

**Comment by frattaro** [comment]
I mean the changelog edits aren't showing up in this PR -- still only 2 commits.

I'm not sure why it's not prompting me to approve the CI workflows for this PR either.

If you can figure it out that's cool, if not I'd suggest abandoning the fork and cloning the repo and branching

**Comment by MizuhoOkimoto** [comment]
Hi @frattaro , I tried many ways to push my change(add: changelog 3.1.3), and I used force-push as a last resort. I usually don't want to use force/hard, but it was the last attempt before cloning the repo again. 
I believe I pushed it and updated the snapshot. Could you please review it?

**Comment by frattaro** [comment]
Can you pull in the latest? I added `pull_request_target` to the CI workflow, maybe it'll trigger for this PR that way

**Review by frattaro — APPROVED** [review]

**Comment by frattaro** [comment]
I'm going to merge this -- but it's strange that the CI workflow isn't running. I assume it's because it's from a fork. Can you please clone/branch next time?

**Comment by MizuhoOkimoto** [comment]
Hi @frattaro , thank you so much. Sorry for taking your time to check CI and this problem. I will make another fork and clone/branch next time!

**Comment by frattaro** [comment]
Thank you too, the contributions are much appreciated -- sorry for the road bumps :)

**Pull request merged**
